name: Test environment variables

on:
  workflow_dispatch:
  pull_request:

env:
  FIRST_VAR: test

jobs:
  test_env_var:
    name: Test env var
    runs-on: ubuntu-22.04
    steps:
      - name: Check var value
        run: echo "$FIRST_VAR"
